StockManagement/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using StockManagement.Filters;
using StockManagement.Models;

namespace StockManagement.Controllers
{
    [TestActionFilter]
    public class PurchasesController : Controller
    {
        private inventoryDBEntities db = new inventoryDBEntities();

        // GET: Purchases
        public ActionResult Index()
        {
            var tblPurchases = db.tblPurchases.Include(t => t.tblProduct).Include(t => t.tblSupplier).Include(t => t.tblWarehouse);
            return View(tblPurchases.ToList());
        }

      
        // GET: Purchases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            if (tblPurchase == null)
            {
                return HttpNotFound();
            }
            return View(tblPurchase);
        }

        // GET: Purchases/Create
        public ActionResult Create()
        {
            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName");
            ViewBag.supplierID = new SelectList(db.tblSuppliers, "supplierID", "supplierName");
            ViewBag.warehouseID = new SelectList(db.tblWarehouses, "warehouseID", "warehouseName");
            return View();
        }

        // POST: Purchases/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "purchaseID,productID,supplierID,warehouseID,purchasePrice,quantity,totalPrice,purchaseDate,description")] tblPurchase tblPurchase)
        {
            //if (ModelState.IsValid)
            //{
            //    db.tblPurchases.Add(tblPurchase);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName", tblPurchase.productID);
            //ViewBag.supplierID = new SelectList(db.tblSuppliers, "supplierID", "supplierName", tblPurchase.supplierID);
            //ViewBag.warehouseID = new SelectList(db.tblWarehouses, "warehouseID", "warehouseName", tblPurchase.warehouseID);
            //return View(tblPurchase);


            if (ModelState.IsValid)
            {
                tblPurchase oReceive = new tblPurchase();
                db.tblPurchases.Add(tblPurchase);
                var oStock = (from o in db.tblStocks where o.productID == tblPurchase.productID select o).FirstOrDefault();
                if (oStock == null)
                {
                    oStock = new tblStock();
                    oStock.productID = tblPurchase.productID;
                    oStock.quantity = tblPurchase.quantity;
                    oStock.status = "Receive";
                    db.tblStocks.Add(oStock);
                }
                else
                {
                    oStock.quantity += tblPurchase.quantity;
                    oStock.status = "Receive";
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblPurchase);
        }


        // GET: Purchases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            if (tblPurchase == null)
            {
                return HttpNotFound();
            }
            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName", tblPurchase.productID);
            ViewBag.supplierID = new SelectList(db.tblSuppliers, "supplierID", "supplierName", tblPurchase.supplierID);
            ViewBag.warehouseID = new SelectList(db.tblWarehouses, "warehouseID", "warehouseName", tblPurchase.warehouseID);
            return View(tblPurchase);
        }

        // POST: Purchases/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "purchaseID,productID,supplierID,warehouseID,purchasePrice,quantity,totalPrice,purchaseDate,description")] tblPurchase tblPurchase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblPurchase).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName", tblPurchase.productID);
            ViewBag.supplierID = new SelectList(db.tblSuppliers, "supplierID", "supplierName", tblPurchase.supplierID);
            ViewBag.warehouseID = new SelectList(db.tblWarehouses, "warehouseID", "warehouseName", tblPurchase.warehouseID);
            return View(tblPurchase);

            //if (ModelState.IsValid)
            //{
            //    tblPurchase oReceive = new tblPurchase();

            //    db.Entry(tblPurchase).State = EntityState.Modified;
            //    var oStock = (from o in db.tblStocks where o.productID == tblPurchase.productID select o).FirstOrDefault();
            //    if (oStock == null)
            //    {
            //        oStock = new tblStock();
            //        oStock.productID = tblPurchase.productID;
            //        oStock.quantity = tblPurchase.quantity;
            //        oStock.status = "Receive";
            //        db.tblStocks.Add(oStock);
            //    }
            //    else
            //    {
            //        oStock.quantity += tblPurchase.quantity;
            //        //db.Entry(tblPurchase).State = EntityState.Modified;
            //        oStock.status = "Receive";
            //    }
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //return View(tblPurchase);

        }

        // GET: Purchases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            if (tblPurchase == null)
            {
                return HttpNotFound();
            }
            return View(tblPurchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            db.tblPurchases.Remove(tblPurchase);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //For Price Show
        [HttpPost]
        public JsonResult GetPrice(int productID)
        {
            decimal? price = db.tblProducts.Where(x => x.productID == productID).Select(X => X.purchasePrice).FirstOrDefault();
            return Json(price);
        }

        #region //For Report
        public ActionResult StockList()
        {
            return View(db.tblStocks.ToList());
        }

        public ActionResult Reports(string ReportType)
        {
            LocalReport localreport = new LocalReport();
            localreport.ReportPath = Server.MapPath("~/Reports/PurchaseReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "PurchaseDataSet";
            reportDataSource.Value = db.tblPurchases.ToList();
            localreport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;
            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "PDF")
            {
                fileNameExtension = "pdf";

            }

            else if (reportType == "Word")
            {
                //fileNameExtension = "docsx";
                fileNameExtension = "docx";
            }
            else
            {
                fileNameExtension = "png";
            }

            string[] streams;
            Warning[] warnings;
            byte[] renderdByte;

            renderdByte = localreport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);


            Response.AddHeader("content-disposition", "attachment;fileName = PurchaseReport." + fileNameExtension);
            return File(renderdByte, fileNameExtension);
        }
        #endregion

    }
}

StockManagement/Views/Purchases/Create.cshtml
@model StockManagement.Models.tblPurchase

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-md-12">
        <div id="boxDivId" class="box box-info box-solid">
            <div class="box-header with-border">
                <h3 class="box-title" style="text-align:center">
                    <span style="clear:both;">
                        <b>
                            Purchase : New Purchase
                        </b>
                    </span>
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            @Html.LabelFor(model => model.productID, "productID", htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.DropDownList("productID", null, htmlAttributes: new { @class = "form-control", @id = "pID", onchange = "getPrice()" })
                            @Html.ValidationMessageFor(model => model.productID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.supplierID, "supplierID", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("supplierID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.supplierID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.warehouseID, "warehouseID", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("warehouseID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.warehouseID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Purchase Price</label>
                            @Html.EditorFor(model => model.purchasePrice, new { htmlAttributes = new { @class = "form-control", @id = "price", @readonly = "readonly", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.purchasePrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Quantity</label>
                            @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control", @id = "qty", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Total Price</label>
                            @Html.EditorFor(model => model.totalPrice, new { htmlAttributes = new { @class = "form-control", @id = "total", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.totalPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Purchase Date</label>
                            @Html.EditorFor(model => model.purchaseDate, new { htmlAttributes = new { @class = "form-control", @id = "total", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.purchaseDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Description</label>
                            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <a class="form-group btn btn-danger btn-block fa fa-arrow-circle-left" href="/Purchases/Index"><span> Back</span></a>
                    </div>
                    <div class="col-md-6">

                    </div>
                    <div class="col-lg-4 col-md-4">
                        <button class="form-group btn btn-primary btn-block" value="Create" type="submit" id="btnPRsave">
                            <i class="fa fa-plus"></i>
                            <span>Create Purchase</span>
                        </button>
                    </div>
                </div>
            </div>

        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    function getTotal() {

        var price = document.getElementById("price").value;
        var qty = document.getElementById("qty").value;
        var total = price * qty;
        document.getElementById("total").value = total;
    }

    //For Price Show
    function getPrice() {
        var ProductID = $('#pID').val()

        /*alert(ProductID)*/
        $.ajax({
            type: "POST",
            url: "/Purchases/GetPrice",
            datatype: "Json",
            data: { productID: ProductID },
            success: function (data) {
                /*alert(data);*/
                $('#price').val(data);
            }
        });
    }

</script>

StockManagement/Views/Purchases/Delete.cshtml
@model StockManagement.Models.tblPurchase

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblPurchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.purchasePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchasePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.purchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProduct.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProduct.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSupplier.supplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSupplier.supplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblWarehouse.warehouseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblWarehouse.warehouseName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-warning" })
</div>
    }
</div>

StockManagement/Views/Purchases/Details.cshtml
@model StockManagement.Models.tblPurchase

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.purchasePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchasePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.purchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProduct.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProduct.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSupplier.supplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSupplier.supplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblWarehouse.warehouseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblWarehouse.warehouseName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.purchaseID }, new { @class = "btn btn-info" }) |
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-warning" })
</p>

StockManagement/Views/Purchases/Edit.cshtml
@model StockManagement.Models.tblPurchase

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-md-12">
        <div id="boxDivId" class="box box-info box-solid">
            <div class="box-header with-border">
                <h3 class="box-title" style="text-align:center">
                    <span style="clear:both;">
                        <b>
                            Purchase : Edit Purchase
                        </b>
                    </span>
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">
                <div class="row">
                    <div class="col-md-8">
                        @Html.HiddenFor(model => model.purchaseID)
                        <div class="form-group">
                            @Html.LabelFor(model => model.productID, "productID", htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.DropDownList("productID", null, htmlAttributes: new { @class = "form-control", @id = "pID", onchange = "getPrice()" })
                            @Html.ValidationMessageFor(model => model.productID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.supplierID, "supplierID", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("supplierID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.supplierID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.warehouseID, "warehouseID", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("warehouseID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.warehouseID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Purchase Price</label>
                            @Html.EditorFor(model => model.purchasePrice, new { htmlAttributes = new { @class = "form-control", @id = "price", @readonly = "readonly", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.purchasePrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Quantity</label>
                            @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly",@id = "qty", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Total Price</label>
                            @Html.EditorFor(model => model.totalPrice, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly",@id = "total", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.totalPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Purchase Date</label>
                            @Html.EditorFor(model => model.purchaseDate, new { htmlAttributes = new { @class = "form-control", @id = "total", onchange = "getTotal()" } })
                            @Html.ValidationMessageFor(model => model.purchaseDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-4">
                        <div class="form-group">
                            <label for="txtDescriptionSlave" class="col-form-label">Description</label>
                            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <a class="form-group btn btn-danger btn-block fa fa-arrow-circle-left" href="/Purchases/Index"><span> Back</span></a>
                    </div>
                    <div class="col-md-6">

                    </div>
                    <div class="col-lg-4 col-md-4">
                        <button class="form-group btn btn-primary btn-block" value="Save" type="submit" id="btnPRsave">
                            <i class="fa fa-plus"></i>
                            <span>Update Purchase</span>
                        </button>
                    </div>
                </div>
            </div>

        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    function getTotal() {

        var price = document.getElementById("price").value;
        var qty = document.getElementById("qty").value;
        var total = price * qty;
        document.getElementById("total").value = total;
    }

    //For Price Show
    function getPrice() {
        var ProductID = $('#pID').val();

        /*alert(ProductID)*/

        $.ajax({
            type: "POST",
            url: "/Purchases/GetPrice",
            datatype: "Json",
            data: { productID: ProductID },
            success: function (data) {
                /*alert(data);*/
                $('#price').val(data);
            }
        });
    }

</script>

StockManagement/Views/Purchases/Index.cshtml
@model IEnumerable<StockManagement.Models.tblPurchase>

@{
    ViewBag.Title = "Index";
}

<br />
<br />
@Html.ActionLink(" Excel", "Reports", new { ReportType = "Excel" }, new { @class = " btn btn-success fa fa-file-excel-o" }) |
@Html.ActionLink(" PDF", "Reports", new { ReportType = "PDF" }, new { @class = " btn btn-success fa fa-file-pdf-o" }) |
@Html.ActionLink(" Word", "Reports", new { ReportType = "Word" }, new { @class = " btn btn-success fa fa-file-word-o" }) |
@Html.ActionLink(" Image", "Reports", new { ReportType = "Image" }, new { @class = " btn btn-success fa fa-picture-o" })
<br />
<br />
<div class="col-md-12">
    @Html.ActionLink(" New Purchase", "Create", "Purchases", new { }, new { @class = "btn btn-primary  fa fa-plus" })
</div>
<br />
<br />
<div>
    <div class="box box-primary">
        <div class="box-body">
            <table border="1" class="table table-bordered table-hover table-striped table-condensed">
                <tr style="font-size:14px">
                    <th>
                        @Html.DisplayNameFor(model => model.tblProduct.productName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.purchasePrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.totalPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.purchaseDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.tblSupplier.supplierName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.tblWarehouse.warehouseName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.description)
                    </th>
                    <th>Action</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblProduct.productName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.purchasePrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.totalPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.purchaseDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblSupplier.supplierName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblWarehouse.warehouseName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.description)
                        </td>
                        <td>
                            @Html.ActionLink(" Edit", "Edit", new { id = item.purchaseID }, new { @class = "btn btn-primary d-inline fa fa-pencil" }) |
                            @Html.ActionLink(" Details", "Details", new { id = item.purchaseID }, new { @class = "btn btn-info d-inline fa fa-info" })|
                            @Html.ActionLink(" Delete", "Delete", new { id = item.purchaseID }, new { @class = "btn btn-danger fa fa-trash-o" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
 </div>