StockManagement/Controllers/WarehousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using PagedList;
using StockManagement.Filters;
using StockManagement.Models;

namespace StockManagement.Controllers
{
    [TestActionFilter]
    public class WarehousesController : Controller
    {
        private inventoryDBEntities db = new inventoryDBEntities();

        // GET: Warehouses
        public ActionResult Index(string searchBy, string search, int? page, string sortBy)
        {
            ViewBag.SortNameParameter = string.IsNullOrEmpty(sortBy) ? "warehouseName desc" : "";
            ViewBag.SortManagerParameter = sortBy == "warehouseManager" ? "warehouseManager desc" : "warehouseManager";

            //For sorting
            var warehouses = db.tblWarehouses.AsQueryable();

            if (searchBy == "warehouseManager")
            {
                warehouses = warehouses.Where(x => x.warehouseManager == search || search == null);
            }
            else
            {
                warehouses = warehouses.Where(x => x.warehouseName.StartsWith(search) || search == null);
            }

            switch (sortBy)
            {
                case "warehouseName desc":
                    warehouses = warehouses.OrderByDescending(x => x.warehouseName);
                    break;
                case "warehouseManager desc":
                    warehouses = warehouses.OrderByDescending(x => x.warehouseManager);
                    break;
                case "warehouseManager":
                    warehouses = warehouses.OrderBy(x => x.warehouseManager);
                    break;
                default:
                    warehouses = warehouses.OrderBy(x => x.warehouseName);
                    break;
            }
            return View(warehouses.ToPagedList(page ?? 1, 3));
        }

        //#region
        //[HttpPost]
        //public ActionResult Index(string searchTerm)
        //{
        //    inventoryDBEntities db = new inventoryDBEntities();
        //    List<tblWarehouse> tblWarehouses;
        //    if (string.IsNullOrEmpty(searchTerm))
        //    {
        //        tblWarehouses = db.tblWarehouses.ToList();
        //    }
        //    else
        //    {
        //        tblWarehouses = db.tblWarehouses.Where(x => x.warehouseName.StartsWith(searchTerm)).ToList();
        //    }
        //    return View(tblWarehouses);
        //}

        //public JsonResult GetWarehouse(string term)
        //{
        //    inventoryDBEntities db = new inventoryDBEntities();
        //    List<string> tblWarehouses;

        //    tblWarehouses = db.tblWarehouses.Where(x => x.warehouseName.StartsWith(term))
        //     .Select(y => y.warehouseName).ToList();

        //    return Json(tblWarehouses, JsonRequestBehavior.AllowGet);
        //}
        //#endregion

        // GET: Warehouses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblWarehouse tblWarehouse = db.tblWarehouses.Find(id);
            if (tblWarehouse == null)
            {
                return HttpNotFound();
            }
            return View(tblWarehouse);
        }

        // GET: Warehouses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Warehouses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "warehouseID,warehouseNo,warehouseName,warehouseManager,address")] tblWarehouse tblWarehouse)
        {
            if (ModelState.IsValid)
            {
                db.tblWarehouses.Add(tblWarehouse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblWarehouse);
        }

        // GET: Warehouses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblWarehouse tblWarehouse = db.tblWarehouses.Find(id);
            if (tblWarehouse == null)
            {
                return HttpNotFound();
            }
            return View(tblWarehouse);
        }

        // POST: Warehouses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "warehouseID,warehouseNo,warehouseName,warehouseManager,address")] tblWarehouse tblWarehouse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblWarehouse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblWarehouse);
        }

        // GET: Warehouses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblWarehouse tblWarehouse = db.tblWarehouses.Find(id);
            if (tblWarehouse == null)
            {
                return HttpNotFound();
            }
            return View(tblWarehouse);
        }

        // POST: Warehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblWarehouse tblWarehouse = db.tblWarehouses.Find(id);
            db.tblWarehouses.Remove(tblWarehouse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #region //For Report
        public ActionResult WarehouseList()
        {
            return View(db.tblWarehouses.ToList());
        }

        public ActionResult Reports(string ReportType)
        {
            LocalReport localreport = new LocalReport();
            localreport.ReportPath = Server.MapPath("~/Reports/WarehouseReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "Warehouse";
            reportDataSource.Value = db.tblWarehouses.ToList();
            localreport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;
            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "PDF")
            {
                fileNameExtension = "pdf";

            }

            else if (reportType == "Word")
            {
                //fileNameExtension = "docsx";
                fileNameExtension = "docx";
            }
            else
            {
                fileNameExtension = "png";
            }

            string[] streams;
            Warning[] warnings;
            byte[] renderdByte;

            renderdByte = localreport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);


            Response.AddHeader("content-disposition", "attachment;fileName = WarehouseReport." + fileNameExtension);
            return File(renderdByte, fileNameExtension);
        }
        #endregion
    }
}

StockManagement/Views/Warehouses/Create.cshtml
@model StockManagement.Models.tblWarehouse

@{
    ViewBag.Title = "Create";
}

<div class="row content-wrapper content">
    <div class="col-md-8">
        <div>
            <section>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Create New Warehouse</h3>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <form role="form">
                            <div class="box-body">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(model => model.warehouseNo, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.warehouseNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.warehouseNo, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.warehouseName, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.warehouseName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.warehouseName, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.warehouseManager, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.warehouseManager, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.warehouseManager, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                                </div>

                            </div>
                            <div class="box-footer">
                                <div class="col-lg-4 col-md-4 pull-right">
                                    <button class="form-group btn btn-primary btn-block " value="Create" type="submit" id="btnPRsave">
                                        <i class="fa fa-plus"></i>
                                        <span>Create Warehouse</span>
                                    </button>
                                </div>
                                <div class="col-md-2">
                                    <a class="form-group btn btn-danger btn-block fa fa-arrow-circle-left" href="/Warehouses/Index"><span> Back</span></a>
                                </div>
                            </div>

                        </form>
                    }
                </div>

            </section>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StockManagement/Views/Warehouses/Delete.cshtml
@model StockManagement.Models.tblWarehouse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.warehouseNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warehouseNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.warehouseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warehouseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.warehouseManager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warehouseManager)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-info" })
</div>
    }
</div>

StockManagement/Views/Warehouses/Details.cshtml
@model StockManagement.Models.tblWarehouse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.warehouseNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warehouseNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.warehouseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warehouseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.warehouseManager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warehouseManager)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.warehouseID }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-info" })
</p>

StockManagement/Views/Warehouses/Edit.cshtml
@model StockManagement.Models.tblWarehouse

@{
    ViewBag.Title = "Edit";
}

<div class="row content-wrapper content">
    <div class="col-md-8">
        <div>
            <section>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Warehouse</h3>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <form role="form">
                            <div class="box-body">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.warehouseID)
                                <div class="form-group">
                                    @Html.LabelFor(model => model.warehouseNo, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.warehouseNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.warehouseNo, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.warehouseName, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.warehouseName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.warehouseName, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.warehouseManager, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.warehouseManager, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.warehouseManager, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                                </div>

                            </div>
                            <div class="box-footer">
                                <div class="col-lg-4 col-md-4 pull-right">
                                    <button class="form-group btn btn-primary btn-block " value="Save" type="submit" id="btnPRsave">
                                        <i class="fa fa-plus"></i>
                                        <span>Update Warehouse</span>
                                    </button>
                                </div>
                                <div class="col-md-2">
                                    <a class="form-group btn btn-danger btn-block fa fa-arrow-circle-left" href="/Warehouses/Index"><span> Back</span></a>
                                </div>
                            </div>

                        </form>
                    }
                </div>

            </section>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StockManagement/Views/Warehouses/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<StockManagement.Models.tblWarehouse>

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />

<div>
    @using (Html.BeginForm("Index", "Warehouses", FormMethod.Get))
    {
        <b>Search By:</b> @Html.RadioButton("searchBy", "warehouseName", true) <text>Warehouse Name</text>
        @Html.RadioButton("searchBy", "warehouseManager") <text>Warehouse Manager</text>
        <div class="pull-right" style="">
            @Html.TextBox("search", null, new { id = "txtSearch", placeholder = "Search.." }) 
            <button type="submit" value="Search" style="background: #2196F3; color: white; font-size: 17px; border: 1px solid grey; border-left: none; "><i class="fa fa-search"></i></button>
        </div>
    }
</div>
<br />
<br />
@Html.ActionLink(" Excel", "Reports", new { ReportType = "Excel" }, new { @class = " btn btn-success fa fa-file-excel-o" }) |
@Html.ActionLink(" PDF", "Reports", new { ReportType = "PDF" }, new { @class = " btn btn-success fa fa-file-pdf-o" }) |
@Html.ActionLink(" Word", "Reports", new { ReportType = "Word" }, new { @class = " btn btn-success fa fa-file-word-o" }) |
@Html.ActionLink(" Image", "Reports", new { ReportType = "Image" }, new { @class = " btn btn-success fa fa-picture-o" })

<br />
<br />
<div class="col-sm-12">
    <a href="/Warehouses/Create" id="createCustomer" class="btn btn-info "><i class="fa fa-plus"></i> New Warehouse</a>
</div>
<hr />

@{
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <table border="1" class="table table-bordered table-hover table-striped table-responsive">
                            <thead>
                                <tr style="font-size:16px">
                                    <th>
                                        @Html.DisplayNameFor(model => model.First().warehouseNo)
                                    </th>
                                    <th>
                                        @Html.ActionLink("warehouseName", "Index", new { sortBy = ViewBag.SortNameParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
                                    </th>
                                    <th>
                                        @Html.ActionLink("warehouseManager", "Index", new { sortBy = ViewBag.SortNameParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.First().address)
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            @*//For Search*@
                            @if (Model.Count() == 0)
                            {
                                <tr>
                                    <td colspan="6" class="bg-danger text-center">No Rows Match for Search criteria</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.warehouseNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.warehouseName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.warehouseManager)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.address)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" Edit", "Edit", new { id = item.warehouseID }, new { @class = "btn btn-primary fa fa-pencil" }) |
                                            @Html.ActionLink(" Details", "Details", new { id = item.warehouseID }, new { @class = "btn btn-success fa fa-info" }) |
                                            @Html.ActionLink(" Delete", "Delete", new { id = item.warehouseID }, new { @class = "btn btn-danger fa fa-trash-o" })
                                        </td>
                                    </tr>
                                }
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

@*//For Pagination*@
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"], sortBy = Request["sortBy"] }),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })