StockManagement/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using StockManagement.Models;

namespace StockManagement.Controllers
{
    public class StocksController : Controller
    {
        private inventoryDBEntities db = new inventoryDBEntities();

        // GET: Stocks
        public ActionResult Index()
        {
            var tblStocks = db.tblStocks.Include(t => t.tblProduct).Include(t => t.tblPurchase);
            return View(tblStocks.ToList());
        }

        // GET: Stocks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblStock tblStock = db.tblStocks.Find(id);
            if (tblStock == null)
            {
                return HttpNotFound();
            }
            return View(tblStock);
        }

        // GET: Stocks/Create
        public ActionResult Create()
        {
            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName");
            ViewBag.purchaseID = new SelectList(db.tblPurchases, "purchaseID", "purchaseID");
            return View();
        }

        // POST: Stocks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "stockID,productID,purchaseID,quantity,status")] tblStock tblStock)
        {
            if (ModelState.IsValid)
            {
                db.tblStocks.Add(tblStock);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName", tblStock.productID);
            ViewBag.purchaseID = new SelectList(db.tblPurchases, "purchaseID", "purchaseID", tblStock.purchaseID);
            return View(tblStock);
        }

        // GET: Stocks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblStock tblStock = db.tblStocks.Find(id);
            if (tblStock == null)
            {
                return HttpNotFound();
            }
            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName", tblStock.productID);
            ViewBag.purchaseID = new SelectList(db.tblPurchases, "purchaseID", "purchaseID", tblStock.purchaseID);
            return View(tblStock);
        }

        // POST: Stocks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "stockID,productID,purchaseID,quantity,status")] tblStock tblStock)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblStock).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.productID = new SelectList(db.tblProducts, "productID", "productName", tblStock.productID);
            ViewBag.purchaseID = new SelectList(db.tblPurchases, "purchaseID", "purchaseID", tblStock.purchaseID);
            return View(tblStock);
        }

        // GET: Stocks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblStock tblStock = db.tblStocks.Find(id);
            if (tblStock == null)
            {
                return HttpNotFound();
            }
            return View(tblStock);
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblStock tblStock = db.tblStocks.Find(id);
            db.tblStocks.Remove(tblStock);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult StockControl(int pID, int quantity)
        {
            string message = "";
            int qty = db.tblStocks.Where(q => q.productID == pID).Select(q => q.quantity).FirstOrDefault();
            if (qty < quantity)
            {
                message = "Sorry! your product is exceed the Sales Limit.";
            }
            return Json(message);
        }

        #region //For Report
        public ActionResult StockList()
        {
            return View(db.tblStocks.ToList());
        }

        public ActionResult Reports(string ReportType)
        {
            LocalReport localreport = new LocalReport();
            localreport.ReportPath = Server.MapPath("~/Reports/StockReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "StockDataSet";
            reportDataSource.Value = db.tblStocks.ToList();
            localreport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;
            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "PDF")
            {
                fileNameExtension = "pdf";

            }

            else if (reportType == "Word")
            {
                //fileNameExtension = "docsx";
                fileNameExtension = "docx";
            }
            else
            {
                fileNameExtension = "png";
            }

            string[] streams;
            Warning[] warnings;
            byte[] renderdByte;

            renderdByte = localreport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);


            Response.AddHeader("content-disposition", "attachment;fileName = stock." + fileNameExtension);
            return File(renderdByte, fileNameExtension);
        }
        #endregion
    }
}

StockManagement/Views/Stocks/Create.cshtml
@model StockManagement.Models.tblStock

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Stock</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.productID, "productID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.productID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.purchaseID, "purchaseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("purchaseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.purchaseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StockManagement/Views/Stocks/Delete.cshtml
@model StockManagement.Models.tblStock

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblStock</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProduct.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProduct.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblPurchase.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblPurchase.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-warning" })
</div>
    }
</div>

StockManagement/Views/Stocks/Details.cshtml
@model StockManagement.Models.tblStock

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tblStock</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProduct.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProduct.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblPurchase.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblPurchase.description)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.stockID }, new { @class = "btn btn-primary" }) |*@
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-warning" })
</p>

StockManagement/Views/Stocks/Edit.cshtml
@model StockManagement.Models.tblStock

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblStock</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.stockID)

        <div class="form-group">
            @Html.LabelFor(model => model.productID, "productID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.productID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.purchaseID, "purchaseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("purchaseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.purchaseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StockManagement/Views/Stocks/Index.cshtml
@model IEnumerable<StockManagement.Models.tblStock>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink(" Excel", "Reports", new { ReportType = "Excel" }, new { @class = " btn btn-success fa fa-file-excel-o" }) |
@Html.ActionLink(" PDF", "Reports", new { ReportType = "PDF" }, new { @class = " btn btn-success fa fa-file-pdf-o" }) |
@Html.ActionLink(" Word", "Reports", new { ReportType = "Word" }, new { @class = " btn btn-success fa fa-file-word-o" }) |
@Html.ActionLink(" Image", "Reports", new { ReportType = "Image" }, new { @class = " btn btn-success fa fa-picture-o" })
<br />
<br />
@*<p>
        @Html.ActionLink("Create New", "Create", "Stocks", new { }, new { @class = "btn btn-primary" })
    </p>
    <br />
    <br />*@
<div class="box box-primary">
    <div class="box-body">
        <table border="1" class="table table-bordered table-hover cell-border table-striped table-responsive">
            <tr style="font-size:16px">
                <th>
                    @Html.DisplayNameFor(model => model.tblProduct.productName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.tblPurchase.description)
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.tblProduct.productName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tblPurchase.description)
                    </td>
                    <td>
                        @*@Html.ActionLink(" Edit", "Edit", new { id = item.stockID }, new { @class = "btn btn-primary fa fa-pencil" }) |*@
                        @Html.ActionLink(" Details", "Details", new { id = item.stockID }, new { @class = "btn btn-info fa fa-info" }) |
                        @Html.ActionLink(" Delete", "Delete", new { id = item.stockID }, new { @class = "btn btn-danger fa fa-trash-o" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>